# name: Trigger auto deployment for ar-viewer

# on:
#   push:
#     branches:
#       - main
#     paths:
#       - '**'
#       - '.github/workflows/ar-viewer-AutoDeployTrigger-8976a704-bca8-4560-86f9-1d444e1ce346.yml'
#   workflow_dispatch:

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest
#     permissions:
#       id-token: write
#       contents: read

#     steps:
#       - name: Checkout to the branch
#         uses: actions/checkout@v2

#       - name: Azure Login
#         uses: azure/login@v1
#         with:
#           client-id: ${{ secrets.ARVIEWER_AZURE_CLIENT_ID }}
#           tenant-id: ${{ secrets.ARVIEWER_AZURE_TENANT_ID }}
#           subscription-id: ${{ secrets.ARVIEWER_AZURE_SUBSCRIPTION_ID }}

#       - name: Build and deploy Container App using Dockerfile
#         uses: azure/container-apps-deploy-action@v2
#         with:
#           appSourcePath: ${{ github.workspace }}
#           dockerfilePath: Dockerfile
#           registryUrl: ${{ secrets.ARVIEWER_REGISTRY_URL }}
#           registryUsername: ${{ secrets.ARVIEWER_REGISTRY_USERNAME }}
#           registryPassword: ${{ secrets.ARVIEWER_REGISTRY_PASSWORD }}
#           containerAppName: ar-viewer
#           resourceGroup: DefaultResourceGroup-WEU
#           imageToBuild: ${{ secrets.ARVIEWER_REGISTRY_URL }}/ar-viewer:${{ github.sha }}

# name: Trigger auto deployment for ar-viewer

# on:
#   push:
#     branches:
#       - main
#     paths:
#       - '**'
#       - '.github/workflows/ar-viewer-AutoDeployTrigger-8976a704-bca8-4560-86f9-1d444e1ce346.yml'
#   workflow_dispatch:

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest
#     permissions:
#       id-token: write
#       contents: read

#     steps:
#       - name: Checkout to the branch
#         uses: actions/checkout@v2

#       - name: Azure Login
#         uses: azure/login@v1
#         with:
#           client-id: ${{ secrets.ARVIEWER_AZURE_CLIENT_ID }}
#           tenant-id: ${{ secrets.ARVIEWER_AZURE_TENANT_ID }}
#           subscription-id: ${{ secrets.ARVIEWER_AZURE_SUBSCRIPTION_ID }}

#       - name: Build and deploy Container App using Dockerfile
#         uses: azure/container-apps-deploy-action@v2
#         with:
#           appSourcePath: ${{ github.workspace }}
#           dockerfilePath: Dockerfile
#           registryUrl: ${{ secrets.ARVIEWER_REGISTRY_URL }}
#           registryUsername: ${{ secrets.ARVIEWER_REGISTRY_USERNAME }}
#           registryPassword: ${{ secrets.ARVIEWER_REGISTRY_PASSWORD }}
#           containerAppName: ar-viewer
#           resourceGroup: DefaultResourceGroup-WEU
#           imageToBuild: ${{ secrets.ARVIEWER_REGISTRY_URL }}/ar-viewer:${{ github.sha }}
